export const KALENDER_META = [
  { name: "Players Championship 1", typ: "ProTour" },
  { name: "Players Championship 2", typ: "ProTour" },
  { name: "Players Championship 3", typ: "ProTour" },
  { name: "UK Open", typ: "Major" },
  { name: "Players Championship 4", typ: "ProTour" },
  { name: "Players Championship 5", typ: "ProTour" },
  { name: "Players Championship 6", typ: "ProTour" },
  { name: "European Tour 1", typ: "EuropeanTour" },
  { name: "European Tour 2", typ: "EuropeanTour" },
  { name: "Premier League Night", typ: "Major" },
  { name: "Players Championship 7", typ: "ProTour" },
  { name: "Players Championship 8", typ: "ProTour" },
  { name: "Players Championship 9", typ: "ProTour" },
  { name: "US Masters", typ: "WorldSeries" },
  { name: "European Tour 3", typ: "EuropeanTour" },
  { name: "European Tour 4", typ: "EuropeanTour" },
  { name: "Players Championship 10", typ: "ProTour" },
  { name: "Players Championship 11", typ: "ProTour" },
  { name: "Players Championship 12", typ: "ProTour" },
  { name: "World Matchplay", typ: "Major" },
  { name: "Players Championship 13", typ: "ProTour" },
  { name: "Players Championship 14", typ: "ProTour" },
  { name: "European Tour 5", typ: "EuropeanTour" },
  { name: "European Tour 6", typ: "EuropeanTour" },
  { name: "Brisbane Masters", typ: "WorldSeries" },
  { name: "Players Championship 15", typ: "ProTour" },
  { name: "Players Championship 16", typ: "ProTour" },
  { name: "World Grand Prix", typ: "Major" },
  { name: "Players Championship 17", typ: "ProTour" },
  { name: "Players Championship 18", typ: "ProTour" },
  { name: "European Championship", typ: "Major" },
  { name: "Players Championship 19", typ: "ProTour" },
  { name: "Players Championship 20", typ: "ProTour" },
  { name: "Grand Slam of Darts", typ: "Major" },
  { name: "Players Championship 21", typ: "ProTour" },
  { name: "Players Championship 22", typ: "ProTour" },
  { name: "Players Championship Finals", typ: "Major" },
  { name: "PDC World Championship", typ: "Major" },
];
